fastlane_version "1.90.0"
default_platform :ios

platform :ios do
  before_all do
    clear_derived_data
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(scheme: "Gaggle")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    gym(scheme: "Gaggle", workspace: "Gaggle.xcworkspace", export_team_id: "726J23ESFP")
    deliver(
      skip_screenshots: true,
      skip_metadata: true
    )
    increment_build_number
    commit_version_bump(
      message: 'Build Version bump by Fastlane',
      xcodeproj: "Gaggle.xcodeproj",
      force: true
    )
    push_to_git_remote(
      force: true
    )
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
    frameit
  end

  error do |lane, exception|

  end
end
